---
title: "Plotly"
author: "Wenshan Qu (wq2160)"
date: "10/28/2021"
output: html_document
---

This page is about plotly examples.

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Let's look at the NYC airbnb data.

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  ) %>% 
  drop_na(stars)
```

## Make a scatterplot

Here's a plotly scatterplot

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price: $", price, "\nRating:", stars)
  ) %>% ## `\n` means changing lines.
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = .5
  )
```

## Plotly boxplot

```{r}
nyc_airbnb %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) %>% 
  plot_ly(
    y = ~price, color = ~neighbourhood, type = "box",
    colors = "viridis"
    )
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

## ggplotly

This is a handy quick way to do, but plotly is better.

```{r}
gg_lat_long = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(gg_lat_long)
```

